spring:
       datasource:
                  url: jdbc:postgresql:aow
                  username: postgres
                  password: dash
       jpa:
          generate-ddl: true
#          create: true